### ISSUE TITLE
[Feature] 支持对指定网段跳过代理认证

### ISSUE THREAD

**Issue by Lighfer** [Lighfer/clash#1]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

比如下面这段配置对来自`127.0.0.1`、`192.168.1.x`、`192.168.103.x`的IP跳过身份认证，而对其他IP仍然进行认证。
```yaml
# config.yml
authentication:
  - "xxx:yyy"
skip-authentication-cidr:
  - "127.0.0.1/32"
  - "192.168.1.0/24"
  - "192.168.103.0/24"
```
